FROM jenkins/jenkins:lts

USER root
# Install dependencies and the .NET 10 SDK
RUN apt-get update && apt-get install -y wget && \
    wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh && \
    chmod +x dotnet-install.sh && \
    ./dotnet-install.sh --channel 10.0 --install-dir /usr/share/dotnet && \
    ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER jenkins
